# SonarQube server connection details
sonar.host.url=http://103.140.142.220:9000/
sonar.login=sqa_761583bdb459aa9d620aef19f8d52a4bc442d786

# Project identification
sonar.projectKey=curveapp-backend
sonar.projectName=curveapp-backend
sonar.projectVersion=1.0

# Source code directories
sonar.sources=.


# Language specific settings
sonar.language=js
sonar.sources.inclusions=**/*.js


# Encoding of source files
sonar.sourceEncoding=UTF-8

# Analysis exclusions (adjust as needed)
#sonar.exclusions=node_modules/**/, coverage/**/

# Coverage reports (for example, if using Istanbul for coverage)
#sonar.javascript.lcov.reportPaths=coverage/lcov-report/lcov.info
